### ISSUE TITLE
Add auth_proxy to /metrics endpoint

### ISSUE THREAD

**Issue by jrcast** [ForgeRock/secret-agent#35]
We should look into hardening/protecting this endpoint. Add back auth_proxy and enable it.

auth_proxy was removed in 4f7cbedbf256d94c13493056c1f9f5b056b18606

**Comment by snarlysodboxer** [comment]
I'm not sure I agree. The metrics should not be exposing any PII or anything otherwise of much use to an attacker, especially since that attacker would already be inside the network/cluster.

I think the auth_proxy is for clusters that aren't using NetworkPolicy, and if you aren't using NetworkPolicy you probably either aren't worried about an attacker seeing this app's metrics or you have another solution in place like Istio/Envoy.

I also don't think we have to add any of that kustomize stuff back to leave metrics enabled and accessible to those who want to use them. I think those were just providing a different want to access the metrics through auth. (Thus the `# Comment the following 4 lines if you want to disable the auth proxy` comment.)

More often than not, prometheus metrics are run unsecured but only exposed over private networks.

**Comment by jrcast** [comment]
Updated the title and description of the ticket

**Comment by jrcast** [comment]
I would bet majority of k8s users out there are not using istio or network policies. It is indeed an internal endpoint so 🤷‍♂️ 

At the very minimum we should document the existence of this endpoint and how to disable it. 
users just need to pass `--metrics-addr=0`
